insert into donations (donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url,
    donor_cause_area_url, notes, affected_countries, affected_states,
    affected_cities, affected_regions, influencer) values
    ('Future Justice Fund','Essie Justice Group',NULL,'2016-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For General Support.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Common Justice',NULL,'2016-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For General Support.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Color Of Change',NULL,'2016-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For Prosecutor Accountability Efforts.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','The Marshall Project',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For General Support.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Civil Rights Corps',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For General Support.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Californians For Safety And Justice',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For California Bail Reform Effort.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Ella Baker Center For Human Rights',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For California Bail Reform Efforts.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Youth Justice Coalition',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For California Bail Reform Efforts.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Communities United For Restorative Youth Justice',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For California Bail Reform Efforts.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Fathers & Families Of San Joaquin',NULL,'2017-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For California Bail Reform Efforts.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Million Voters Project',NULL,'2016-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For California Proposition 57 Advocacy.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Alliance For Safety And Justice',NULL,'2016-01-01','year','donation log','Criminal Justice Reform','https://www.futurejusticefund.org/criminaljustice','https://www.futurejusticefund.org/criminaljustice','For Crime Survivor Organizing Convenings.',NULL,NULL,NULL,NULL,'Chloe Cockburn')
    ,('Future Justice Fund','Economic Security Project',NULL,'2017-01-01','year','donation log','Income Security','https://www.futurejusticefund.org/incomesecurity','https://www.futurejusticefund.org/incomesecurity','For General Support; Voter Perception Research, a project of David Binder Research; Listen First Tour, a project of Mia Birdsong.',NULL,NULL,NULL,NULL,NULL)
    ,('Future Justice Fund','GiveDirectly',NULL,'2016-01-01','year','donation log','Income Security','https://www.futurejusticefund.org/incomesecurity','https://www.futurejusticefund.org/incomesecurity','For Basic Income Study.',NULL,NULL,NULL,NULL,NULL)
;
